### ISSUE TITLE
two dots in a row in email-link

### ISSUE THREAD

**Issue by subnoodle** [codesource/typo3-cdsrc_bepwreset#25] opened 2020-10-07 14:52 UTC
Dear developer,

this extension works wonderful generally.

I ran into one issue regarding the link in the pwd-reset-mail.
I adapted the fluidtemplate for the email content.
`    Um den Prozess abzuschließen, klicken Sie bitte auf folgenden Link: {url -> f:format.raw()}
    Dieser Link ist gültig bis zum {validity -> f:format.date(format:'d.m.Y H:i')} Uhr.
`
So, the tags stayed the same, just translated.

Now, it occures, that users SOMETIMES receives mails with a link like:
<subdomain>..<domain>.<tld>/<path/s...>
Means: double dot after subdomain.

We tried configuring baseUrl in different ways.
As far i could see, it does not play any role, variable "url" is taken from:
`            'url' => sprintf(
                '%s/typo3/index.php?commandRS=change&hash=%s',
                GeneralUtility::getIndpEnv('TYPO3_REQUEST_HOST'),
                $hash
`
(from file web/typo3conf/ext/cdsrc_bepwreset/Classes/Tool/ResetTool.php, line 105)

Using Typo 8, i think the new "normalizedParameters" are not available from the new requestService object.

Can you imagine, where this error can be emerge from?

Thank you very much,
Sam

**Comment by codesource** [comment] 2021-05-07 07:45
Hello,

Sorry for the delayed answer to that.
I watched the code and did some try. I have not been able to reproduce this bug.
`GeneralUtility::getIndpEnv('TYPO3_REQUEST_HOST')` use `GeneralUtility::getIndpEnv('HTTP_HOST')` to construct the URL.

This last one use the HTTP_HOST (https://tools.ietf.org/html/rfc7230#section-5.4) or the "reverseProxyIP" if configured in TYPO3.
https://github.com/TYPO3/TYPO3.CMS/blob/87dd80d5810e1e8f559b5a9584f423c4dada4544/typo3/sysext/core/Classes/Utility/GeneralUtility.php#L2513

Do you have a "reverseProxyIP" configured in TYPO3?

**Comment by codesource** [comment] 2022-04-19 12:30
Closing due to no answer

**Closed as completed by codesource** 2022-04-19 12:30 UTC
